import { Inter } from "next/font/google";
import "./globals.css";
import "react-quill/dist/quill.snow.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="flex gap-5">
                    <Link href="/">Home</Link>
                    <Link href="/blog">Blog</Link>
                </div>
                {children}
            </body>
        </html>
    );
}
